### PR TITLE
Update color-coordinating-shoes-102.txt

### PR DESCRIPTION
**Pull request by 837951602**

### CODE REVIEW

**Comment by 12345ieee** [comment]
Really nice work, you're incredible.
Keeping the max in the 1st MC, really, I'm amazed.

I've shaved a trivial cycles and pushed in this branch, see if you find anything else, otherwise I'll add it.

**Comment by 837951602** [comment]
Now use less energy than 101. Does 101 have similar optimization to make it shorter?

**Comment by 837951602** [comment]
Also there's enough space, so it's easy if adding some component make some value better
[img]https://i.stack.imgur.com/Uu56T.png[/img]

**Comment by 12345ieee** [comment]
The 101 can be made faster by unrolling more the right loop, I'll do that later.

As for using more components, the power record is out of the question and the lines one probably doesn't benefit.

I added this solution.

**Pull request closed without merging**
