### PR TITLE
Create animated-esports-sign-202.txt (16/75/18)

### PR DESCRIPTION
**Pull request by 837951602**
Warning: Impossible wiring, not sure if allowed here

### CODE REVIEW

**Comment by 12345ieee** [comment]
No, sorry, no impossible wires.

**Comment by 837951602** [comment]
If so some score may be fake?

**Comment by 12345ieee** [comment]
What do you mean? All the files here have possible wiring.

Can you please post a full file for the last comment of https://github.com/12345ieee/shenzhenIO-leaderboard/pull/3#issuecomment-413153836 , or we'll forget about it.

**Comment by 837951602** [comment]
In https://www.reddit.com/r/shenzhenIO/wiki/index some are without code and seem to be offical score board

**Comment by 12345ieee** [comment]
I know the people that hold those scores, and I'm pretty sure they didn't cheat, but indeed you're right.

The reason I've yet to make a post on the subreddit about the wiki is that I'm waiting for u/hersmunch, who hold a lot of the file-less to share his scores with me, so the LB would be mostly documented.

After I made the post, if there's interest for it I may put impossible wirings in their category, like they do in TIS with cheating solutions.

**Pull request closed without merging**
