### PR TITLE
Update neural-processor-logic-board-301.txt

### PR DESCRIPTION
**Pull request by 837951602**
I guess we should have an issue on small optimizations, or maybe trivial ones, rather than have a branch for each?

### CODE REVIEW

**Comment by 12345ieee** [comment]
No, please keep using pull requests.

As you can see even this one turned into a bigger one.

**Comment by 837951602** [comment]
> As you can see even this one turned into a bigger one.

No, the sameness on two is only that thay're solutions for same level. They should have been separated, but if I do so I'm afraid to get confused sometimes

**Comment by 12345ieee** [comment]
It's ok, I don't care how you split them, just that you put every change in pull requests.

**Comment by 12345ieee** [comment]
I've actually never finished this level, so I just ran the solution without even checking them for ideas/improvements.

Merged in f23be2a48b6336 & ae101ecaeeec6dcaf8bb9 .

**Pull request closed without merging**
