### PR TITLE
Power 975

### PR DESCRIPTION
**Pull request by Thineboot**
Being a similar solution I guess you'll once again won't credit me...

### CODE REVIEW

**Comment by 12345ieee** [comment]
No, this time you'll get credited, because you improved a named record.

**Comment by 837951602** [comment]
If it's a skip first tick how does that work?

**Comment by 12345ieee** [comment]
I thought that this was some heavier change, but indeed it's just a "skip first tick" at its core.

Just be honest, if you think your change is significant put your name in the file, otherwise leave the name that was there before.

**Comment by 12345ieee** [comment]
Added in 8ad8f6f .

**Pull request closed without merging**
