### PR TITLE
Update cold-storage-robot-101.txt

### PR DESCRIPTION
**Pull request by saroj1am**

### CODE REVIEW

**Comment by saroj1am** [comment]
There is also an alternative with 14/450/32: just replace the "gen p1 acc 0" line in UC4 (at x = 10, y = 6) with the two lines "mov 100 p1" and "slp acc".

**Comment by saroj1am** [comment]
Sorry for the mess. The "Create..." file is the up-to-date one. An alternative with 14/444/31 can be obtained from it by replacing the line "gen p1 x1 x0" in UC4 by the two lines "mov x0 p1" and "slp x1"; at the same time you have to replace the line "mov 0 x3" in UC6 by "mov 100 x3".

**Comment by saroj1am** [comment]
Ok, this should be it! Nice and simple solution; much better than the previous elaborate one.

**Comment by 12345ieee** [comment]
Thanks, merged in 1516ada .

**Pull request closed without merging**
