### PR TITLE
Better Cost solution for Sushi Robot

### PR DESCRIPTION
**Pull request by bkimmett**
I've created a version of the sushi robot with the same cost as the leaderboard version, but with better power usage (albeit with worse lines of code).

Please credit the design to Quackles and GuavaMoment.

### CODE REVIEW

**Comment by bkimmett** [comment]
It occurs to me I might have messed up with the file numbering and title, seeing as I do actually tie the previous branch (it beats me in lines of code, where I beat it in power usage). Sorry about that.

**Comment by bkimmett** [comment]
There we go. The previous solution is still -101.txt, while my solution is -102.txt.

**Comment by 12345ieee** [comment]
The last state is ok, you just got the numbering wrong.

Your new file has to be 101, because it's power optimized, while the other file will become 102.

I'll also not be able to credit this solution to you, because Sushi Robot 12€ is an unnamed record (as in, I can't know what the original author of the 12€ had, maybe it was even better than both here), I'd be able to credit it if you had beat 12€ (which IMHO is not possible).

I'll add it this evening, thanks for submitting.

It's also nice to hear from GuavaMoment, I've just posted a call for a tournament host for the 2019 SC tournament, maybe he wants another go 😄  .

**Comment by bkimmett** [comment]
Thanks! :) I'm Lets Playing the game you can follow along with my progress here - https://forums.somethingawful.com/showthread.php?threadid=3865959 - and GuavaMoment can also be contacted through the forum if you want to chat with him.

**Comment by 12345ieee** [comment]
Ah, you're the Rasputin guy, great stuff.

Merged in 1984d262931ae2dadd85324ac0cbec .

Closing.

**Comment by 12345ieee** [comment]
I've read your "blog" a bit, the power score the game gives you isn't the average power across tests, it's the worst power across tests.

**Comment by bkimmett** [comment]
Huh! So it's more like the EXAPUNKS behavior... that's good to know, though there's no good way to debug it in SIO 'cause the game doesn't let you see which test run had that cost.

(The 'average' is partly a storytelling flavor thing, seeing as it's supposed to be in-universe. Maybe the Engineer doesn't know...)

Thanks! :)

**Pull request closed without merging**
