### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by 837951602**

### CODE REVIEW

**Comment by 12345ieee** [comment]
Merged as b21be32 .

**Comment by 837951602** [comment]
```
[name] New design 2
[puzzle] Sz022
[production-cost] 800
[power-usage] 167
[lines-of-code] 10

[traces] 
......................
......................
......................
......................
......................
......................
..............155554..
..........955555C.....
..........34.14.3414..
..9555555554.14...14..
..2..........14...14..
......................
......................
......................

[chip] 
[type] UC6
[x] 11
[y] 3
[code] 
- slx x1
- mov x1 x3
- mov 7 acc
- mov 100 p1
+ mov x2 x0
+ mov x2 x3
+ slp 1
  tgt acc 0
+ sub 1
- mov x0 p1

[chip] 
[type] BANK
[x] 14
[y] 3
[rom] 
0,536,0,11,101,6,0,105,9,0,1,10,40,2

[chip] 
[type] DX3
[x] 17
[y] 3

[chip] 
[type] BRIDGE
[x] 14
[y] 5


```

**Comment by 12345ieee** [comment]
I've shaved 5 more cycles and added it.

I feel like a line is removable, but couln't find a way.

**Comment by 837951602** [comment]
8 Lines, $8

```
- slx x1
- mov x1 x3
- mov 7 acc
+ mov x2 x0
+ mov x2 x3
+ gen p1 1 0
  tgt acc x0
+ sub 1
```

**Comment by 12345ieee** [comment]
That indeed works, but please provide a full file.

**Comment by 837951602** [comment]
https://paste.ubuntu.com/p/cKmRfj3cXX/

**Comment by 12345ieee** [comment]
Thanks!

You may also want to add me on steam ( https://steamcommunity.com/id/12345ieee/ ), to talk more easily than via GH issues.

**Pull request closed without merging**
